# PHP/Apache image
web:
  # Use the Dockerfile instead of a default image
  build: ./docker/php
  # Map inside ports to the host system
  ports:
    - 8765:80
  volumes:
    - ./webroot:/var/www/html
    - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
  links:
    - db:database

# MySQL image
db:
  # Use official MariaDB iamge
  image: mariadb
  # Make storage permanent by storing everything in a mounted local folder
  volumes:
    - ./db:/var/lib/mysql
  # Set up DB credential and initial database
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: drupal
