# PHP/Apache image
web:
  # Use the Dockerfile instead of a default image
  build: ./docker/php
  # Map inside ports to the host system
  ports:
    - 8888:80
  # Mount local files and folders
  volumes:
    # Mount web source to Apache docroot
    - ./webroot:/var/www/html
    # Mount local php.ini
    - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
  links:
    - db:database

# MySQL image
db:
  # Use official MariaDB iamge
  image: mariadb
  # Make storage permanent by storing everything in a mounted local folder
  volumes:
    - ./db:/var/lib/mysql
  # Set up DB credential and initial database
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: drupal
